-- Applies the French translations to rows that already exist (the seed does
-- the same for fresh databases). Merged into `translations`, matched on the
-- natural key, and safe to run on any environment: rows that aren't there are
-- simply not touched.

UPDATE "Country" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"name":"Sénégal"}}$q$::jsonb WHERE "name" = $q$Senegal$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Raquettes"}}$q$::jsonb WHERE "code" = $q$RACKET$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Chaussures"}}$q$::jsonb WHERE "code" = $q$SHOES$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Vêtements"}}$q$::jsonb WHERE "code" = $q$APPAREL$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Sacs"}}$q$::jsonb WHERE "code" = $q$BAGS$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Balles"}}$q$::jsonb WHERE "code" = $q$BALLS$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Accessoires"}}$q$::jsonb WHERE "code" = $q$ACCESSORIES$q$;
UPDATE "ProductCategory" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"label":"Autres"}}$q$::jsonb WHERE "code" = $q$OTHER$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Courts de tennis du complexe sportif du stade Léopold Sédar Senghor, où se joue l’une des compétitions de club les plus disputées de Dakar."}}$q$::jsonb WHERE "name" = $q$Stade L.S.S$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Association Sportive des Travailleurs Unis, un club de quartier historique à l’ambiance conviviale et chaleureuse."}}$q$::jsonb WHERE "name" = $q$ASTU$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Un club omnisports haut de gamme à Dakar, avec un solide programme de tennis, une académie de coaching et des courts bien entretenus."}}$q$::jsonb WHERE "name" = $q$Olympic Club$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Le Tennis Club de Dakar, l’un des plus anciens et des plus prestigieux clubs de la ville, réputé pour ses compétitions par équipes."}}$q$::jsonb WHERE "name" = $q$T.C.D$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Association Sportive et d’Athlétisme, un club familial aux tarifs accessibles avec un programme junior en pleine croissance."}}$q$::jsonb WHERE "name" = $q$ASAC$q$;
UPDATE "Club" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"description":"Des courts situés dans l’enceinte de l’hôtel King Fahd Palace, dans un cadre de villégiature avec des équipements de premier plan."}}$q$::jsonb WHERE "name" = $q$King Fahd$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Open · Simple","description":"Le plus grand week-end amateur de la saison. Élimination directe, meilleur des trois sets, un vrai tableau et une remise des trophées sous les projecteurs."}}$q$::jsonb WHERE "name" = $q$Teranga Cup$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Hommes & Femmes · 3.0–4.5","description":"Deux tableaux, un week-end. Jouez à votre niveau, rencontrez des joueurs de tous les clubs de la ville et gagnez des points pour le classement de la saison."}}$q$::jsonb WHERE "name" = $q$Dakar Open Amateur$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Intermédiaire · Simple","description":"De longs échanges, des glissades et l’air marin. Une poule unique pour que chacun joue au moins trois matchs."}}$q$::jsonb WHERE "name" = $q$Petite-Côte Clay Classic$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Tous niveaux · Simple","description":"Des matchs après le travail sous les projecteurs. Format court, ambiance détendue, grosse ambiance."}}$q$::jsonb WHERE "name" = $q$Corniche Night Series$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Seniors 45+ · Simple","description":"L’expérience l’emporte sur la puissance. Un tournoi amical mais âprement disputé pour les joueurs de plus de 45 ans."}}$q$::jsonb WHERE "name" = $q$Seniors 45+ Masters$q$;
UPDATE "Competition" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"category":"Open · Simple","description":"L’ouverture de la saison, jouée le mois dernier — découvrez qui a soulevé le trophée."}}$q$::jsonb WHERE "name" = $q$Trophée de la Rentrée$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"Coupe Teranga","slides":[{"headline":"La Coupe Teranga est lancée","body":"Les huitièmes de finale sont en cours au club."},{"headline":"Suivez le tableau","body":"Qui joue contre qui, et quand.","ctaLabel":"Voir le tournoi"}]}}$q$::jsonb WHERE "title" = $q$Teranga Cup$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"Dakar Open","slides":[{"headline":"Les inscriptions sont ouvertes","body":"Le Dakar Open Amateur commence dans une semaine."},{"headline":"Deux tableaux, 64 joueurs","body":"Jouez à votre niveau et gagnez des points pour la saison."},{"headline":"Réservez votre place","ctaLabel":"S’inscrire"}]}}$q$::jsonb WHERE "title" = $q$Dakar Open$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"Conseils de service","slides":[{"headline":"Lancez plus haut","body":"Un lancer de balle régulier fait 80 % d’un bon service."},{"headline":"Fléchissez les genoux","body":"La puissance vient des jambes, pas du bras."},{"headline":"Terminez le geste","body":"Laissez la raquette finir sa course en travers du corps."}]}}$q$::jsonb WHERE "title" = $q$Serve tips$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"Réservez un court","slides":[{"headline":"Les créneaux du soir partent vite","body":"Réservez avant 18 h pour être tranquille.","ctaLabel":"Trouver un court"}]}}$q$::jsonb WHERE "title" = $q$Book a court$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"La course de la saison","slides":[{"headline":"Chaque match compte","body":"Une victoire officielle rapporte 100 points, un match amical 50."},{"headline":"Grimpez les échelons","body":"De Débutant à Champion — suivez votre progression.","ctaLabel":"Ma saison"}]}}$q$::jsonb WHERE "title" = $q$Season race$q$;
UPDATE "Story" SET "translations" = COALESCE("translations", '{}'::jsonb) || $q${"fr":{"title":"Bons plans matériel","slides":[{"headline":"Des raquettes toutes fraîches sur le marché","body":"Du matériel d’occasion de joueurs près de chez vous.","ctaLabel":"Parcourir le marché"}]}}$q$::jsonb WHERE "title" = $q$Gear deals$q$;

UPDATE "Notification" SET "messageKey" = 'registrationOpen' WHERE "messageKey" IS NULL AND "title" = $q$Registration is open$q$ AND "body" = $q$Dakar Open Amateur starts in a week — grab your spot.$q$;
UPDATE "Notification" SET "messageKey" = 'niceWin' WHERE "messageKey" IS NULL AND "title" = $q$Nice win!$q$ AND "body" = $q$Your last match earned you season points. See where you stand.$q$;
UPDATE "Notification" SET "messageKey" = 'courtReminder' WHERE "messageKey" IS NULL AND "title" = $q$Court reminder$q$ AND "body" = $q$Bookings are easier to keep with a partner — invite someone.$q$;
UPDATE "Notification" SET "messageKey" = 'newGear' WHERE "messageKey" IS NULL AND "title" = $q$New gear near you$q$ AND "body" = $q$Fresh rackets and shoes were just listed in the market.$q$;
UPDATE "Notification" SET "messageKey" = 'welcome' WHERE "messageKey" IS NULL AND "title" = $q$Welcome to the club$q$ AND "body" = $q$Book courts, score your matches and climb the season ranking.$q$;
